"""message_hash

Revision ID: f9cf68e90372
Revises: ccc6a27eb0cf
Create Date: 2026-02-23 23:34:57.962847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9cf68e90372'
down_revision: Union[str, Sequence[str], None] = 'ccc6a27eb0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_hash', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'message_hash')
    # ### end Alembic commands ###
